name: 'Wat'
inputs:
  token:
    default: ${{ github.token }}
    required: true
runs:
  using: 'composite'
  steps:
    - run: curl -v -H 'Accept: application/vnd.github.v3+json' -H "Authorization: Bearer $INPUT_TOKEN" https://api.github.com/rate_limit
      shell: bash
      env:
        INPUT_TOKEN: ${{ inputs.token }}
